config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :courses do
    resources :course_users
  end

  resources :user_sessions
  resources :users
  resources :employees

  get 'contacts' => 'pages#contacts', :as => :contacts

  post 'users/:id' => 'users#toggle_admin'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'register' => 'users#new', :as => :register

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :require_admin
  before_action :set_employee, only: [:edit, :show, :edit, :update, :destroy]

  # This method is used for the index employees page
  def index
    @employees = User.where(admin: true)
  end

  # This method is used for the show employee page
  def show
  end

  # This method is used for the new employee page
  def new
    @employee = User.new
  end

  # This method is used for the edit employee page
  def edit
  end

  # This method will be trigged if there is a post request with the create method
  def create
    @employee = User.new(employee_params).toggle(:admin)

    if @employee.save
      redirect_to employees_path, notice: 'Employee was successfully created'
    else
      render action: 'new'
    end
  end

  # This method will be trigged if there is a post request with the update method
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        render action: 'edit'
      end
    end
  end

  # This method will be trigged if there is a post request with the destroy method
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_path, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # This method will find an employee with an id param and define the instance variable @employee to it
  def set_employee
    @employee = User.find(params[:id])
  end

  # This method wil require from params the hash user and permit params to have: email, password, password_confirmation
  def employee_params
    params.require(:user).permit(:email, :roepnaam, :tussenvoegsel, :achternaam, :adres, :woonplaats, :telefoon, :password, :password_confirmation)
  end
end

app/views/employees/_form.html.erb
<%= form_for(@employee, url: employees_path) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email, "Email (gebruiksnaam)" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :roepnaam %><br>
    <%= f.text_field :roepnaam %>
  </div>
  <div class="field">
    <%= f.label :tussenvoegsel %><br>
    <%= f.text_field :tussenvoegsel %>
  </div>
  <div class="field">
    <%= f.label :achternaam %><br>
    <%= f.text_field :achternaam %>
  </div>
  <div class="field">
    <%= f.label :adres %><br>
    <%= f.text_field :adres %>
  </div>
  <div class="field">
    <%= f.label :woonplaats %><br>
    <%= f.text_field :woonplaats %>
  </div>
  <div class="field">
    <%= f.label :telefoon %><br>
    <%= f.text_field :telefoon %>
  </div>
  <div class="field">
   <%= f.label :password %><br />
   <%= f.password_field :password %>
  </div>
  <div class="field">
     <%= f.label :password_confirmation %><br />
     <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>
<br>
<div class="context">
  <table>
    <thead>
      <tr>
        <th>Email</th>
        <th>Roepnaam</th>
        <th>Tussenvoegsel</th>
        <th>Achternaam</th>
        <th>Adres</th>
        <th>Woonplaats</th>
        <th>Telefoonnummer</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.email %></td>
          <td><%= employee.roepnaam %></td>
          <td><%= employee.tussenvoegsel %></td>
          <td><%= employee.achternaam %></td>
          <td><%= employee.adres %></td>
          <td><%= employee.woonplaats %></td>
          <td><%= employee.telefoon %></td>
          <td><%= link_to 'Show', employee %></td>
          <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
          <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Employee', new_employee_path %>
</div>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>