config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :courses do
    resources :course_users
  end

  resources :user_sessions
  resources :users
  resources :employees

  get 'contacts' => 'pages#contacts', :as => :contacts

  post 'users/:id' => 'users#toggle_admin'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'register' => 'users#new', :as => :register

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :course_users, dependent: :destroy
  has_many :courses, -> { distinct }, through: :course_users

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

  validates :email, uniqueness: true, presence: true
  validates :roepnaam, :achternaam, presence: true

  def full_name
    "#{roepnaam} #{tussenvoegsel} #{achternaam}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :toggle_admin]
  before_action :require_admin, only: [:index, :destroy, :toggle_admin]
  before_action :require_not_logged_in_or_admin, only: [:new, :create]
  before_action :check_user, only: [:show, :edit, :update]
  skip_before_action :require_login, only: [:new, :create]

  # This method is used for the index users page
  def index
    @users = User.all
  end

  # This method is used for the show user page
  def show
  end

  # This method is used for the new user page
  def new
    @user = User.new
  end

  # This method is used for the edit user page
  def edit
  end

  # This method will be trigged if there is a post request with the create method
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: 'User was successfully created'
    else
      render action: 'new'
    end
  end

# This method will be trigged if there is a post request with the update method
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        render action: 'edit'
      end
    end
  end

  # This method will be trigged if there is a post request with the destroy method
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_admin
    @user.toggle!(:admin)
    redirect_to users_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def check_user
      if !current_user.admin?
        redirect_to(users_path, alert: 'Geen bevoegdheid') if current_user != @user
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :roepnaam, :tussenvoegsel, :achternaam, :adres, :woonplaats, :telefoon, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email, "Email (gebruiksnaam)" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :roepnaam %><br>
    <%= f.text_field :roepnaam %>
  </div>
  <div class="field">
    <%= f.label :tussenvoegsel %><br>
    <%= f.text_field :tussenvoegsel %>
  </div>
  <div class="field">
    <%= f.label :achternaam %><br>
    <%= f.text_field :achternaam %>
  </div>
  <div class="field">
    <%= f.label :adres %><br>
    <%= f.text_field :adres %>
  </div>
  <div class="field">
    <%= f.label :woonplaats %><br>
    <%= f.text_field :woonplaats %>
  </div>
  <div class="field">
    <%= f.label :telefoon %><br>
    <%= f.text_field :telefoon %>
  </div>
  <div class="field">
   <%= f.label :password %><br />
   <%= f.password_field :password %>
</div>
<div class="field">
   <%= f.label :password_confirmation %><br />
   <%= f.password_field :password_confirmation %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<div class="context">
  <%= render 'form' %>

  <%= link_to 'Show', @user %> |
  <% if current_user.admin? %>
    <%= link_to 'Back', users_path %>
  <% else %>
    <%= link_to 'Back', root_path %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Listing Users</h1>
<div class="context">
  <table>
    <thead>
      <tr>
        <th>Email</th>
        <th>Roepnaam</th>
        <th>Tussenvoegsel</th>
        <th>Achternaam</th>
        <th>Adres</th>
        <th>Woonplaats</th>
        <th>Telefoonnummer</th>
        <th>Is medewerker</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.order(admin: :desc).each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.roepnaam %></td>
          <td><%= user.tussenvoegsel %></td>
          <td><%= user.achternaam %></td>
          <td><%= user.adres %></td>
          <td><%= user.woonplaats %></td>
          <td><%= user.telefoon %></td>
          <td><%= user.admin? ? 'Ja' : 'Nee' %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% if current_user.admin? %>
            <td><%= link_to user.admin? ? "Verwijder medewerker" : "Maak medewerker", user, method: :toggle_admin %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<h1>New User</h1><br>
<div class="context">
  <%= render 'form' %>
  <br>
  <% if current_user.nil? %>
    <% if !current_user.nil? %>
      <% if current_user.admin? %>
        <%= link_to 'Back', users_path %>
      <% end %>
    <% end %>
    <%= link_to 'Back', root_path %>
  <% end %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Roepnaam:</strong>
  <%= @user.roepnaam %>
</p>
<p>
  <strong>Tussenvoegsel:</strong>
  <%= @user.tussenvoegsel %>
</p>
<p>
  <strong>Achternaam:</strong>
  <%= @user.achternaam %>
</p>
<p>
  <strong>Adres:</strong>
  <%= @user.adres %>
</p>
<p>
  <strong>Woonplaats:</strong>
  <%= @user.woonplaats %>
</p>
<p>
  <strong>Telefoonnummer:</strong>
  <%= @user.telefoon %>
</p>

<div class="context">
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <% if current_user.admin? %>
    <% if @user.admin? %>
      <%= link_to 'Back', employees_path %>
    <% else %>
      <%= link_to 'Back', users_path %>
    <% end %>
  <% else %>
    <%= link_to 'Back', root_path %>
  <% end %>
</div>