config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :courses do
    resources :course_users
  end

  resources :user_sessions
  resources :users
  resources :employees

  get 'contacts' => 'pages#contacts', :as => :contacts

  post 'users/:id' => 'users#toggle_admin'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'register' => 'users#new', :as => :register

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:edit, :new, :create, :update, :destroy]
  skip_before_action :require_login, only: [:show, :index]

  # This method is used for the index courses page
  def index
    @courses = Course.all
  end

  # This method is used for the new course page
  def new
    @course = Course.new
  end

  # This method is used for the edit course page
  def edit
  end

  # This method is used for the show course page
  def show
  end

  # This method will be trigged if there is a post request with the create method
  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to @course, notice: 'Course was successfully created'
    else
      render action: 'new'
    end
  end

  # This method will be trigged if there is a post request with the update method
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        render action: 'edit'
      end
    end
  end

  # This method will be trigged if there is a post request with the destroy method
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # This method will find a course with an id param and define the instance variable @course to it
  def set_course
    @course = Course.find(params[:id])
  end

  # This method wil require from params the hash course and permit params to have: begindatum, einddatum, soortcourse_id
  def course_params
    params.require(:course).permit(:begindatum, :einddatum, :soortcourse_id)
  end
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :begindatum %><br>
    <%= f.date_field :begindatum %>
  </div>
  <div class="field">
   <%= f.label :einddatum %><br />
   <%= f.date_field :einddatum %>
  </div>
  <div class="field">
    <%= f.label :soortcourse %>
    <%= f.collection_select(:soortcourse_id, Soortcourse.all, :id, :prijs) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>
<div class="context">
  <%= render 'form' %>

  <%= link_to 'Show', @course %> |
  <%= link_to 'Back', courses_path %>
</div>

app/views/courses/index.html.erb
<h1>Listing courses</h1>
<br>
<div class="context">
  <table>
    <thead>
      <tr>
        <th>Soort cursus</th>
        <th>Prijs</th>
        <th>Begindatum</th>
        <th>Einddatum</th>
        <% if !current_user.nil? %>
          <th>Ingeschreven</th>
        <% end %>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td><%= course.soortcourse.cursussoort %></td>
          <td><%= number_to_currency(course.soortcourse.prijs, :unit => "€") %></td>
          <td><%= course.begindatum %></td>
          <td><%= course.einddatum %></td>
          <% if !current_user.nil? %>
            <% if current_user.admin? %>
              <td><%= pluralize(course.course_users.count, 'user') %></td>
            <% else %>
              <td><%= course.users.include?(current_user) ? 'Ja' : 'Nee' %></td>
            <% end %>
          <% end %>
          <td><%= link_to 'Show', course %></td>
          <% if !current_user.nil? %>
            <% if current_user.admin? %>
              <td><%= link_to 'Edit', edit_course_path(course) %></td>
              <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if !current_user.nil? %>
    <% if current_user.admin? %>
      <%= link_to 'New Course', new_course_path %>
    <% end %>
  <% end %>
</div>

app/views/courses/new.html.erb
<h1>New Course</h1>
<div class="context">
  <%= render 'form' %>
  <%= link_to 'Back', courses_path %>
</div>

app/views/courses/show.html.erb
<h1><%= @course.soortcourse.cursussoort %></h1><br>

<p>
  <strong>Prijs:</strong>
  <%= number_to_currency(@course.soortcourse.prijs, :unit => "€") %>
</p>

<p>
  <strong>Begin datum:</strong>
  <%= @course.begindatum %>
</p>

<p>
  <strong>Eind datum:</strong>
  <%= @course.einddatum %>
</p>
<div class="context">
  <% if !current_user.nil? %>
    <% if !current_user.admin? %>
      <% if current_user.courses.include?(@course) %>
          <%= form_for [@course, @course.course_users.build] do |f| %>
            <%= f.submit "Afmelden" %>
          <% end %>
      <% else %>
        <%= form_for [@course, @course.course_users.build] do |f| %>
          <%= f.submit "Aanmelden" %>
        <% end %>
      <% end %>
    <% else %>
      <!-- Als admin mag jij je niet inschrijven -->
      <!-- Dit kan echter wel met een POST request -->
    <% end %>

    <br>

    <% if current_user.admin? %>
      <h1>Listing Course Users(<%= @course.course_users.count %>)</h1><br>

        <table>
          <thead>
            <tr>
              <th>Email</th>
            </tr>
          </thead>

          <tbody>
            <% @course.course_users.each_with_index do |course_user, idx| %>
              <tr>
                <td><%= "#{idx + 1}. #{course_user.user.email}" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>

        <%= link_to 'Edit', edit_course_path(@course) %> |
    <% end %>
  <% end %>

  <%= link_to 'Back', courses_path %>
</div>