config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :courses do
    resources :course_users
  end

  resources :user_sessions
  resources :users
  resources :employees

  get 'contacts' => 'pages#contacts', :as => :contacts

  post 'users/:id' => 'users#toggle_admin'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'register' => 'users#new', :as => :register

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutorial</title>
      <%= stylesheet_link_tag    "application" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
  </head>
  <body>

  <header class="container">
    <nav>
      <ul id="navlist">
        <% if flash[:notice] %>
          <li><div id="notice"><%= flash[:notice] %></div></li>
        <% elsif  flash[:alert] %>
          <li><div id="alert"><%= flash[:alert] %></div></li>
        <% end %>
        <% if current_user %>
          <li><%= nav_link "Edit Profile", edit_user_path(current_user.id) %></li>
          <li><%= link_to "Logout", :logout, method: :post %></li>
        <% else %>
          <li><%= nav_link "Register", register_path %></li>
          <li><%= nav_link "Login", login_path %></li>
        <% end %>
        <li><div id="title">Omega</div></li>
      </ul>
    </nav>


  </header>

  <section class="container">
    <div class="sidebar1">
      <div id="sidebarmenu">
        <ul>
          <li><%= nav_link "Home", root_path %></li>
          <li><%= nav_link "Courses", courses_path %></li>
          <% if !current_user.nil? %>
            <% if current_user.admin? %>
              <li><%= nav_link "Users", users_path %></li>
              <li><%= nav_link "Employees", employees_path %></li>
            <% end %>
          <% end %>
          <li><%= nav_link "Contacts", contacts_path %></li>
        </ul>
      </div>
    </div>

    <div class="content">
      <p><%= yield %></p>
    </div>
  </section>

  <footer class="container">
    <p>Copyright &copy; Omega. All rights reserved.
  </footer>

  </body>
</html>